DATASET:
  TRAIN:
    TYPE: 'Freihand_CustomDataset'
    ROOT: ''
    IMG_PREFIX: ''
    ANN: ''
    AUG:
      FLIP: true
      ROT_FACTOR: 45
      SCALE_FACTOR: 0.25
      NUM_JOINTS_HALF_BODY: 3
      PROB_HALF_BODY: 0.3
    root_dir: "/home/louxd/dataset/FreiHand"
    root_dir_autodl: "/root/dataset"
    split0: "FreiHAND_pub_v2/training"
    split1: "FreiHAND_pub_v2"
    split2: "training"
    mode: "train"
  VAL:
    TYPE: 'Freihand_CustomDataset'
    ROOT: ''
    IMG_PREFIX: ''
    ANN: ''
    root_dir: "/home/louxd/dataset/FreiHand"
    root_dir_autodl: "/root/dataset"
    split0: "FreiHAND_pub_v2_eval/evaluation"
    split1: "FreiHAND_pub_v2_eval"
    split2: "evaluation"
    mode: "eval"
    paint: true
  TEST:
    TYPE: 'Freihand_CustomDataset'
    ROOT: ''
    IMG_PREFIX: ''
    DET_FILE: './exp/json/test_det_rcnn.json'
    ANN: ''
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 21
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'RegressFlow'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_FC_FILTERS:
  - -1
  HIDDEN_LIST: -1
  NUM_LAYERS: 50
LOSS:
  TYPE: 'RLELoss'
TEST:
  HEATMAP2COORD: 'coord'
TRAIN:
  WORLD_SIZE: 8
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 270
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200
  PRE_TRAINED: true